import { Car } from "./types";

export const SEED_CARS: Car[] = [
  {
    id: "sc-001",
    brand: "Maruti Suzuki",
    model: "Swift VXI",
    year: 2021,
    price: 612000,
    km: 28450,
    fuel: "Petrol",
    transmission: "Manual",
    owners: 1,
    location: "Bengaluru",
    bodyType: "Hatchback",
    insurance: "Comprehensive, valid till Mar 2027",
    color: "#e2504b",
    description:
      "Single-owner Swift in excellent condition, full service history, non-accidental.",
    featured: true,
    status: "Live",
  },
  {
    id: "sc-002",
    brand: "Hyundai",
    model: "Creta SX",
    year: 2020,
    price: 1245000,
    km: 41200,
    fuel: "Diesel",
    transmission: "Automatic",
    owners: 1,
    location: "Pune",
    bodyType: "SUV",
    insurance: "Comprehensive, valid till Jan 2027",
    color: "#2b6cb0",
    description:
      "Top-spec Creta with sunroof, ventilated seats and automatic transmission.",
    featured: true,
    status: "Live",
  },
  {
    id: "sc-003",
    brand: "Tata",
    model: "Nexon XZ+",
    year: 2022,
    price: 895000,
    km: 15300,
    fuel: "Petrol",
    transmission: "Manual",
    owners: 1,
    location: "Mumbai",
    bodyType: "SUV",
    insurance: "Comprehensive, valid till Jun 2027",
    color: "#38761d",
    description:
      "5-star safety rated Nexon, low mileage, still under manufacturer warranty.",
    status: "Live",
  },
  {
    id: "sc-004",
    brand: "Honda",
    model: "City ZX",
    year: 2019,
    price: 875000,
    km: 52000,
    fuel: "Petrol",
    transmission: "Automatic",
    owners: 2,
    location: "Chennai",
    bodyType: "Sedan",
    insurance: "Third-party, valid till Nov 2026",
    color: "#b45309",
    description: "Well-maintained City with CVT gearbox and sunroof.",
    status: "Live",
  },
  {
    id: "sc-005",
    brand: "Toyota",
    model: "Innova Crysta GX",
    year: 2020,
    price: 1895000,
    km: 63500,
    fuel: "Diesel",
    transmission: "Manual",
    owners: 1,
    location: "Hyderabad",
    bodyType: "MUV",
    insurance: "Comprehensive, valid till Feb 2027",
    color: "#4a5568",
    description: "7-seater family favourite, recently serviced, new tyres.",
    featured: true,
    status: "Live",
  },
  {
    id: "sc-006",
    brand: "Mahindra",
    model: "XUV700 AX7",
    year: 2023,
    price: 2150000,
    km: 9800,
    fuel: "Diesel",
    transmission: "Automatic",
    owners: 1,
    location: "Delhi",
    bodyType: "SUV",
    insurance: "Comprehensive, valid till Sep 2027",
    color: "#1a202c",
    description: "Loaded XUV700 with ADAS, panoramic sunroof, like new.",
    status: "Live",
  },
  {
    id: "sc-007",
    brand: "Kia",
    model: "Seltos HTX",
    year: 2021,
    price: 1180000,
    km: 33200,
    fuel: "Petrol",
    transmission: "Manual",
    owners: 1,
    location: "Ahmedabad",
    bodyType: "SUV",
    insurance: "Comprehensive, valid till Apr 2027",
    color: "#c026d3",
    description: "Feature-packed Seltos, ventilated seats, Bose audio.",
    status: "Live",
  },
  {
    id: "sc-008",
    brand: "Volkswagen",
    model: "Polo Highline",
    year: 2018,
    price: 585000,
    km: 48900,
    fuel: "Petrol",
    transmission: "Manual",
    owners: 2,
    location: "Kolkata",
    bodyType: "Hatchback",
    insurance: "Third-party, valid till Aug 2026",
    color: "#0369a1",
    description: "German engineering, solid build, great handling.",
    status: "Live",
  },
  {
    id: "sc-009",
    brand: "Maruti Suzuki",
    model: "Baleno Alpha",
    year: 2022,
    price: 745000,
    km: 19700,
    fuel: "Petrol",
    transmission: "Automatic",
    owners: 1,
    location: "Bengaluru",
    bodyType: "Hatchback",
    insurance: "Comprehensive, valid till May 2027",
    color: "#ca8a04",
    description: "Top variant Baleno with AMT, head-up display, LED lights.",
    status: "Live",
  },
  {
    id: "sc-010",
    brand: "Hyundai",
    model: "i20 Sportz",
    year: 2021,
    price: 695000,
    km: 26400,
    fuel: "Petrol",
    transmission: "Manual",
    owners: 1,
    location: "Jaipur",
    bodyType: "Hatchback",
    insurance: "Comprehensive, valid till Dec 2026",
    color: "#dc2626",
    description: "Sporty hatchback, sunroof, premium interiors.",
    status: "Live",
  },
  {
    id: "sc-011",
    brand: "Tata",
    model: "Punch Creative",
    year: 2023,
    price: 725000,
    km: 8100,
    fuel: "Petrol",
    transmission: "Manual",
    owners: 1,
    location: "Pune",
    bodyType: "SUV",
    insurance: "Comprehensive, valid till Oct 2027",
    color: "#059669",
    description: "Micro-SUV with 5-star GNCAP rating, barely used.",
    status: "Live",
  },
  {
    id: "sc-012",
    brand: "Renault",
    model: "Kwid RXT",
    year: 2019,
    price: 385000,
    km: 35600,
    fuel: "Petrol",
    transmission: "Manual",
    owners: 1,
    location: "Lucknow",
    bodyType: "Hatchback",
    insurance: "Third-party, valid till Jul 2026",
    color: "#7c3aed",
    description: "Budget-friendly hatchback, great mileage, easy to maintain.",
    status: "Live",
  },
  {
    id: "sc-013",
    brand: "Skoda",
    model: "Rapid Ambition",
    year: 2018,
    price: 545000,
    km: 61200,
    fuel: "Petrol",
    transmission: "Manual",
    owners: 2,
    location: "Chandigarh",
    bodyType: "Sedan",
    insurance: "Third-party, valid till Sep 2026",
    color: "#0f766e",
    description: "Reliable sedan with a comfortable ride and solid chassis.",
    status: "Live",
  },
  {
    id: "sc-014",
    brand: "MG",
    model: "Astor Sharp",
    year: 2022,
    price: 1395000,
    km: 21000,
    fuel: "Petrol",
    transmission: "Automatic",
    owners: 1,
    location: "Mumbai",
    bodyType: "SUV",
    insurance: "Comprehensive, valid till Jan 2028",
    color: "#ea580c",
    description: "AI-connected SUV with panoramic sunroof and ADAS.",
    status: "Live",
  },
];

export function formatPrice(price: number): string {
  if (price >= 100000) {
    return `₹${(price / 100000).toFixed(2)} Lakh`;
  }
  return `₹${price.toLocaleString("en-IN")}`;
}
